
trigger:
- master
- main

resources:
- repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '13.x'
        displayName: 'Install Node.js'

      - script: 
          npm install
        displayName: 'npm install'

      - script: 
          npm run build
        displayName: 'npm build'

      - task: CopyFiles@2
        displayName: 'Copy files'
        inputs:
          sourceFolder: 'dist' 
          Contents: '**/*'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          cleanTargetFolder: true

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
        inputs: 
          pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
                

            